- name: configuring DB server - MySql
  hosts: db
  become: yes
  vars_prompt:
    name: db_root_password
    prompt: please enter your db root password
    private: no
  tasks:
    - name: installing mysql-server 
      ansible.builtin.dnf:
        name: mysql-server
        state: present
    - name:  systemctl enable/start mysqld
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: yes
    - name: mysql root password
      ansible.builtin.command: "mysql_secure_installation --set-root-pass {{ db_root_password }}
      